### ISSUE TITLE
http_response_time_seconds dose not exist!

### ISSUE THREAD

**Issue by rahimi-raz** [martin-helmich/prometheus-nginxlog-exporter#145] opened 2020-09-19 18:55 UTC
**Describe the issue**
First of all thank you for this useful exporter.
I have installed nginxlog_exporter and do the configuration based on guide lines, everything seems correct just the metric  http_response_time_seconds not exist. 
I need to know this metric should be available in last version of exporter?
what is the issue that I can not catch this metric?
Thanks for support.

**Configuration file** (remove section, if not applicable):

```
# Insert the contents of your configuration file
```
**Nginx log format:** 
log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"'
                             'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';

**nginxlog_exporter.yml**
enable_experimental: true
listen:
  port: 4041
  address: "127.0.0.1"

consul:
  enable: false

namespaces:
  - name: service
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" rt=$request_time uct=$upstream_connect_time uht=$upstream_header_time urt=$upstream_response_time"
    source:
      files:
        - /var/log/nginx/access.log
    labels:
      service: ""
      environment: ""
      hostname: "apibeta"
    relabel_configs:
        - target_label: request
          from: request
          split: 2
          matches:
          - regexp: "^/billing/.*"
            replacement: "/billing"

    histogram_buckets: [.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10]

  - name: apibeta
    format: "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" rt=$request_time uct=$upstream_connect_time uht=$upstream_header_time urt=$upstream_response_time"
    source:
      files:
        - /var/log/nginx/access.log
    labels:
      service: ""
      environment: ""
      hostname: "apibeta"

**Example log file** (remove section, if not applicable):

```
# Insert some sample access logs that help reproduce the behavior
# IMPORANT: Please make sure to anonymize any PII like IP addresses and usernames!
```

**Metrics output** (remove section, if not applicable):

```
# Please post the output of the exporter's /metrics endpoint, if applicable
```

**Exporter output** (remove section, if not applicable):

```
# Please post the output of the exporter itself, if applicable
```
![service](https://user-images.githubusercontent.com/48246414/93686759-baf3c900-facd-11ea-8a2f-e8e180f94f17.jpg)
![api](https://user-images.githubusercontent.com/48246414/93686822-3786a780-face-11ea-8a22-7155fb3440d4.jpg)

**Environment**:

- Exporter version: v1.4.0
- OS :centos7
- Deployment method (e.g. Docker image, deb/rpm package, self-compiled, ...): package
- Others:nginx version: nginx/1.9.9

**Comment by martin-helmich** [comment] 2020-09-19 20:07
Duplicate of #120 (fixed in #136 and released in 1.7.1). Please update to [1.7.1](https://github.com/martin-helmich/prometheus-nginxlog-exporter/releases/tag/v1.7.1); if the error should persist in that version, feel free to reopen the issue.

**Closed by martin-helmich** 2020-09-19 20:07 UTC
Labels: question
