### ISSUE TITLE
Error while trying to run application via command line

### ISSUE THREAD

**Issue by Keramblock** [martin-helmich/prometheus-nginxlog-exporter#55] opened 2018-11-14 14:51 UTC
**Issue type**: Support request

**What happened**:
I got error(see below), while trying to start the application via commandline.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy nginx with provided log format and generate some logs
2. Start it with command below

**Other important information**:
```hcl
# Nginx log config:
    log_format mtail '$remote_addr - $remote_user "$time_local" '
                     '"$request" $status $body_bytes_sent '
                     '"$http_referer" "$http_user_agent" '
                     'rt="$request_time" uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
```
**Configuration file** (remove section, if not applicable):

```hcl
# Please post the contents of your configuration file, here
# Was started via comandline
/prometheus-nginxlog-exporter
-format="$remote_addr - $remote_user \"$time_local\" \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" rt=\"$request_time\" uct=\"$upstream_connect_time\" uht=\"$upstream_header_time\" urt=\"$upstream_response_time\""
-listen-port=9114
-namespace=nginx
/tmp/nginx-logs/access.log 
```

**Example log file** (remove section, if not applicable):

```hcl
# Please post an excerpt of a log file that can be used to reproduce the error
# Keep the excerpt as short as possible and make sure to redact any sensitive data.
 using configuration {{%!s(int=9114) 0.0.0.0} {%!s(bool=false)     {  []}} [{nginx [/tmp/nginx-logs/access.log] "$remote_addr - $remote_user \"$time_local\" \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" rt=\"$request_time\" uct=\"$upstream_connect_time\" uht=\"$upstream_header_time\" urt=\"$upstream_response_time\"" map[] [] [] []}] %!s(bool=false)}
starting listener for namespace nginx
running HTTP server on address 0.0.0.0:9114
panic: regexp: Compile(`^"(?P&lt;remote_addr&gt;[^ ]*) - (?P&lt;remote_user&gt;[^ ]*) \\"(?P&lt;time_local&gt;[^\]*)\\" \\"(?P&lt;request&gt;[^\]*)\\" (?P&lt;status&gt;[^ ]*) (?P&lt;body_bytes_sent&gt;[^ ]*) \\"(?P&lt;http_referer&gt;[^\]*)\\" \\"(?P&lt;http_user_agent&gt;[^\]*)\\" rt=\\"(?P&lt;request_time&gt;[^\]*)\\" uct=\\"(?P&lt;upstream_connect_time&gt;[^\]*)\\" uht=\\"(?P&lt;upstream_header_time&gt;[^\]*)\\" urt=\\"(?P&lt;upstream_response_time&gt;[^\]*)\\""$`): error parsing regexp: missing closing ]: `[^\]*)\\" \\"(?P&lt;http_user_agent&gt;[^\]*)\\" rt=\\"(?P&lt;request_time&gt;[^\]*)\\" uct=\\"(?P&lt;upstream_connect_time&gt;[^\]*)\\" uht=\\"(?P&lt;upstream_header_time&gt;[^\]*)\\" urt=\\"(?P&lt;upstream_response_time&gt;[^\]*)\\""$`
goroutine 8 [running]:
regexp.MustCompile(0xc420166180, 0x176, 0xc420037e38)
	/usr/local/go/src/regexp/regexp.go:240 +0x171
github.com/martin-helmich/prometheus-nginxlog-exporter/vendor/github.com/satyrius/gonx.NewParser(0x7ffec5480396, 0xec, 0xc420028708)
	/go/src/github.com/martin-helmich/prometheus-nginxlog-exporter/vendor/github.com/satyrius/gonx/parser.go:27 +0x19a
main.main.func2(0x7ffec54804a0, 0x5, 0xc42000e180, 0x1, 0x1, 0x7ffec5480396, 0xec, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/martin-helmich/prometheus-nginxlog-exporter/main.go:174 +0x4d
created by main.main
	/go/src/github.com/martin-helmich/prometheus-nginxlog-exporter/main.go:173 +0x5db 
```

**Environment**:
- Exporter version: quay.io/martinhelmich/prometheus-nginxlog-exporter:latest (on 9/nov)
- OS (e.g. from /etc/os-release): GKE(coreOS probably)
- Others: As far as I can get the error is in "[^\]* part of regex: https://regex101.com/r/YTSx9W/1

**Comment by martin-helmich** [comment] 2018-12-19 17:50
Cannot reproduce. In my tests, your log format is translated to the regular expression `^(?P<remote_addr>[^ ]*) - (?P<remote_user>[^ ]*) "(?P<time_local>[^"]*)" "(?P<request>[^"]*)" (?P<status>[^ ]*) (?P<body_bytes_sent>[^ ]*) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)" rt="(?P<request_time>[^"]*)" uct="(?P<upstream_connect_time>[^"]*)" uht="(?P<upstream_header_time>[^"]*)" urt="(?P<upstream_response_time>[^"]*)"`, which works without issue.

Are you _absolutely_ sure that you entered the command above in a POXIS-compliant shell (like bash or zsh)? From your error output, it looks like your command line passed the entire string (including surrounding quotes and quote escape characters) to the exporter, which is most likely the cause of this issue.

Closing for now. Feel free to reopen.

**Closed by martin-helmich** 2018-12-19 17:50 UTC
