### ISSUE TITLE
error while parsing $request_time: value '-' could not be parsed into float

### ISSUE THREAD

**Issue by dodysw** [martin-helmich/prometheus-nginxlog-exporter#226] opened 2021-11-22 17:07 UTC
**Describe the bug**
got the following error:
error while parsing $request_time: value '-' could not be parsed into float

**To Reproduce**

**Expected behavior**
No error thrown

**Configuration file** (remove section, if not applicable):

```
...
    format: '$remote_addr - $upstream_cache_status [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$request_time" "$upstream" "$service" "$opaque_path"'
...
```

**Example log file** (remove section, if not applicable):

```
10.20.30.40 - HIT [23/Nov/2021:00:01:14 +0700] "POST /blah/_count HTTP/1.1" 200 91 "-" "myclient" "-" "-" "blah-service" ""
```

**Environment**:

- Exporter version: latest version today

**Comment by martin-helmich** [comment] 2021-11-22 17:33
Duplicate of #224

**Closed by martin-helmich** 2021-11-22 17:33 UTC
Labels: bug
